Repository SOPT-all/36-COLLABORATION-SERVER-WATCHAPEDIA, pull requests merged in 2025-05, with the labels that each got.

#2 [FEAT] 이슈템플릿 및 PR 템플릿 구현
  .github/ISSUE_TEMPLATES/feature.md
  .github/ISSUE_TEMPLATES/fix.md
  .github/ISSUE_TEMPLATES/hotfix.md
  .github/ISSUE_TEMPLATES/refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :sparkles: feature

#4 [FEAT] CICD 구현
  .github/workflows/dev_CD.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :office_worker: cicd

#5 [FIX] docker-compose.yml 수정
  .github/workflows/dev_CD.yml
Labels: :wrench: fix

#7 [FEAT] DB 연결
  .github/workflows/dev_CI.yml
  .gitignore
  build.gradle
  src/main/resources/application.yml
Labels: :sparkles: feature

#15 [FEAT] CorsConfig 구현
  src/main/java/or/sopt/soptwatcha/config/CorsConfig.java
Labels: :sparkles: feature

#18 [FEAT] 취향저격 추천 작품 조회 API 구현
  .gitignore
  build.gradle
  src/main/java/or/sopt/soptwatcha/common/exception/ErrorCode.java
  src/main/java/or/sopt/soptwatcha/controller/MovieController.java
  src/main/java/or/sopt/soptwatcha/domain/Keyword.java
  src/main/java/or/sopt/soptwatcha/domain/Movie.java
  src/main/java/or/sopt/soptwatcha/domain/UpperCategory.java
  src/main/java/or/sopt/soptwatcha/domain/common/enums/Category.java
  src/main/java/or/sopt/soptwatcha/domain/common/enums/IsPositive.java
  src/main/java/or/sopt/soptwatcha/dto/response/GetPreferenceMoviesListResponse.java
  src/main/java/or/sopt/soptwatcha/dto/response/GetPreferenceMoviesResponse.java
  src/main/java/or/sopt/soptwatcha/dto/response/KeywordRecommendationGroupResponse.java
  src/main/java/or/sopt/soptwatcha/dto/response/KeywordResponseDTO.java
  src/main/java/or/sopt/soptwatcha/repository/CommentKeywordRepository.java
  src/main/java/or/sopt/soptwatcha/repository/CommentRepository.java
  src/main/java/or/sopt/soptwatcha/repository/KeywordRepository.java
  src/main/java/or/sopt/soptwatcha/repository/MovieKeywordRepository.java
  src/main/java/or/sopt/soptwatcha/service/MovieService.java
  src/main/java/or/sopt/soptwatcha/service/MovieServiceImpl.java
  src/test/java/or/sopt/soptwatcha/SoptWatchaApplicationTests.java
  src/test/java/or/sopt/soptwatcha/service/MovieServiceImplTest.java
Labels: :sparkles: feature

#20 [FEAT] 탑랭킹 조회 API 및 개봉 예정작 조회 API 구현
  src/main/java/or/sopt/soptwatcha/controller/MovieController.java
  src/main/java/or/sopt/soptwatcha/domain/Keyword.java
  src/main/java/or/sopt/soptwatcha/domain/common/enums/Category.java
  src/main/java/or/sopt/soptwatcha/domain/common/enums/UpperCategory.java
  src/main/java/or/sopt/soptwatcha/dto/response/GetMovieSoonResponseDTO.java
  src/main/java/or/sopt/soptwatcha/dto/response/GetMovieTopRankingResponseDTO.java
  src/main/java/or/sopt/soptwatcha/repository/MovieRepository.java
  src/main/java/or/sopt/soptwatcha/service/MovieService.java
  src/main/java/or/sopt/soptwatcha/service/MovieServiceImpl.java
  src/test/java/or/sopt/soptwatcha/service/MovieServiceImplTest.java
Labels: :sparkles: feature

#23 [FEAT] 영화 상세정보 조회 API 구현
  src/main/java/or/sopt/soptwatcha/controller/MovieController.java
  src/main/java/or/sopt/soptwatcha/domain/common/enums/FilmCountry.java
  src/main/java/or/sopt/soptwatcha/domain/common/enums/Role.java
  src/main/java/or/sopt/soptwatcha/dto/response/ArtistResponseDTO.java
  src/main/java/or/sopt/soptwatcha/dto/response/MovieDetailResponseDTO.java
  src/main/java/or/sopt/soptwatcha/repository/GenreRepository.java
  src/main/java/or/sopt/soptwatcha/repository/MovieArtistRepository.java
  src/main/java/or/sopt/soptwatcha/repository/MovieGenreRepository.java
  src/main/java/or/sopt/soptwatcha/repository/MovieImageRepository.java
  src/main/java/or/sopt/soptwatcha/service/MovieService.java
  src/main/java/or/sopt/soptwatcha/service/MovieServiceImpl.java
  src/main/java/or/sopt/soptwatcha/util/TimeFormatUtil.java
Labels: :sparkles: feature

#28 [FEAT] 영화 인기 코멘트 조회 API 구현
  src/main/java/or/sopt/soptwatcha/common/exception/ErrorCode.java
  src/main/java/or/sopt/soptwatcha/controller/CommentController.java
  src/main/java/or/sopt/soptwatcha/dto/response/CommentResponseDTO.java
  src/main/java/or/sopt/soptwatcha/repository/CommentRepository.java
  src/main/java/or/sopt/soptwatcha/service/CommentService.java
Labels: :sparkles: feature

#29 [FEAT] 영화 코멘트 작성 API 구현
  src/main/java/or/sopt/soptwatcha/common/exception/ErrorCode.java
  src/main/java/or/sopt/soptwatcha/controller/CommentController.java
  src/main/java/or/sopt/soptwatcha/domain/Comment.java
  src/main/java/or/sopt/soptwatcha/domain/CommentKeyword.java
  src/main/java/or/sopt/soptwatcha/dto/request/CommentCreateRequestDTO.java
  src/main/java/or/sopt/soptwatcha/dto/response/CommentCreateResponseDTO.java
  src/main/java/or/sopt/soptwatcha/repository/KeywordRepository.java
  src/main/java/or/sopt/soptwatcha/service/CommentService.java
Labels: :sparkles: feature

#31 [FIX] 선호 태그 리스트 반환 추가
  src/main/java/or/sopt/soptwatcha/domain/common/enums/FilmCountry.java
  src/main/java/or/sopt/soptwatcha/dto/response/MovieDetailResponseDTO.java
Labels: :wrench: fix

#35 [FIX] 공개예정조회 API 업로드 일 기준으로 수정
  src/main/java/or/sopt/soptwatcha/config/SwaggerConfig.java
  src/main/java/or/sopt/soptwatcha/domain/Movie.java
  src/main/java/or/sopt/soptwatcha/repository/MovieRepository.java
  src/main/java/or/sopt/soptwatcha/service/MovieServiceImpl.java
Labels: :wrench: fix
